services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  back:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./back:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres?schema=public
      PORT: "3000"
    command: sh -c "npm ci && npm run start:dev"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  front:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:3000
      HOST: 0.0.0.0
      PORT: "5173"
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - back

volumes:
  postgres_data: